#/usr/bin/perl
use strict;
use warnings;
use Cwd;

#   This code is generated by Akanksha Pandey at University of Florida                   #
# 1.It converts a column wise GTR matrix 421 values into a GGTR 20X20 matrix along with amino acid frequency values to a text file                              #
# 2. It only uses a column wise GTR matrix 421 values as input file #
# 3. Requires input file in cwd
my $dir = getcwd();
my @fields =("EXP","BUR","HELIX","SHEET","COIL");

foreach my $class(@fields)
{
my $input_file = $class . ".txt";
my $output_file = $class . ".dat";
open(my $FH1,"<","$dir/$input_file") or die "Couldn't read $input_file\n";
{
open(my $FH2, ">>","$dir/$output_file") or die "Couldn't write to $output_file\n";
{
my $count = 1;
while(my $line =<$FH1>)  #read each line (row in GTR matrix)
{
	chomp($line);
	if($count % 20 == 0)
	{
		print"\n";
		print $FH2 "\n";
	}
	else
	{
	print"$line\t";
	print $FH2 "$line ";
	}
	$count++
}
}
}
}